### ISSUE TITLE
[BUG] Sensors not loading + Connection error

### ISSUE THREAD

**Issue by SevenNines** [LarsK1/hass_solvis_control#1]
The heating is already implementet via modbus, so it can't be a wrong modbusconfig.

In my opinion the scrennshots say everything, if you need more info let me know.

![image](https://github.com/LarsK1/hass_solvis_control/assets/82905320/2ef19bb2-9791-48e5-9c01-3093ec7608c8)

![image](https://github.com/LarsK1/hass_solvis_control/assets/82905320/502e9d8e-b244-4059-aba6-4a0882fcaac8)

**Comment by SevenNines** [comment]
Its Solvis Ben
![image](https://github.com/LarsK1/hass_solvis_control/assets/82905320/c55a796d-228c-4a45-8485-f586c4e19479)
![image](https://github.com/LarsK1/hass_solvis_control/assets/82905320/d7345fd6-3792-41b3-beb6-bb76730ad410)

**Comment by LarsK1** [comment]
Okay, how's you're Ben connected (WiFi or LAN)? Please try to press the button under the control panel  on oyur solvis to turn it off, afterwards wait 10s, repress the button to turn it on. Then wait 5 minutes, usually it then works again.

**Comment by SevenNines** [comment]
Hello,
sorry for the late reply.
Apparently only one connection is allowed at a time. After a restart, the sensors were supplied with measured values.
Thank you

**Comment by LarsK1** [comment]
Hi,
thanks for confirming.
