### ISSUE TITLE
@LarsK1 beide werden in kW gemessen (siehe "Übersicht" im Solvis-Portal, was ich zur Verifizierung der Adressen genutzt habe)

### ISSUE THREAD

**Issue by zefu59** [LarsK1/hass_solvis_control#16]
@LarsK1 beide werden in kW gemessen (siehe "Übersicht" im Solvis-Portal, was ich zur Verifizierung der Adressen genutzt habe)

_Originally posted by @zefu59 in https://github.com/LarsK1/hass_solvis_control/issues/9#issuecomment-2327239850_

**Comment by zefu59** [comment]
kW ist die korrekte Einheit für die Leistung (siehe Brennerleistung). Die (benötigte/erzeugte) Energie in kWh wird dann durch Multiplizieren mit der Dauer errechnet. Also noch eine kleine Korrektur in const.py. Danke

**Comment by LarsK1** [comment]
Sorry für die späte Rückmeldung. Ist gefixt.
