### ISSUE TITLE
[BUG] correct unit for "Elektrische Wärmepumpenleistung" is kW (not kWh)

### ISSUE THREAD

**Issue by larsneo** [LarsK1/hass_solvis_control#31]
**Version of the plugin**
1.1.0-beta5

 **Home-Assistant Version**
2024.10.1

**Enviroment (Docker, HAOS, ...)**
Home Assistant green

**Describe the bug**
Wrong unit for adress #33545 in last update

**To Reproduce**
Update to latest beta-version

**Expected behavior**
Display of "elektrische Wärmepumpenleistung" in kW (not kWh)

**Additional context**
    ModbusFieldConfig(  # elektrische Wärmepumenleistung
        name="elek_waermepumpe_leistung",
        address=33545,
        unit="kW",

**Comment by LarsK1** [comment]
@kwithus @larsneo I'm pretty unsure about this one. 

Can you please give me detailed information about, why you want which unit? Since I don't have a heat pump I can't text myself.

**Comment by larsneo** [comment]
verkürzt gesagt: Kilowatt beschreibt die Leistung, Kilowattstunden die Arbeit.
Langfassung: https://www.bmwk-energiewende.de/EWD/Redaktion/Newsletter/2016/12/Meldung/direkt-erklaert.html

Die elektrische Aufnahmeleistung p(el) und die thermische 
Leistung p(therm) der Wärmepumpe sind also beide jeweils in kW anzugeben, der "Verbrauch" bzw. die "Erzeugung" über eine bestimmte Zeit wäre dann kWh.

![mia-leistung](https://github.com/user-attachments/assets/67a4a141-c177-4f67-96a3-1fa8c5159c8b)

**Comment by kwithus** [comment]
I am sure, you are absolutely correct. However, HA expects the kWh in order to include an entity into the energy statistics, e.g. to be shown on the energy dashboard

**Comment by larsneo** [comment]
nope, heat pump and e.g. wallbox should use "watt" (or kilowatt) in the energy dashboard
![energie-dashboard](https://github.com/user-attachments/assets/d440bbfe-64d6-4a21-99ee-65f75784cb0a)

**Comment by kwithus** [comment]
that’s strange, as my HA tells me something differently 

![image](https://github.com/user-attachments/assets/535c7081-ee11-4ff2-b00e-1c2ff89ff986)

**Comment by kwithus** [comment]
<img width="1133" alt="image" src="https://github.com/user-attachments/assets/dbfd1b04-180c-455d-b809-0c1f866de7d8">



I use this config for the heatpump and was able to add it
    `ModbusFieldConfig(  # elektrische Wärmepumenleistung
        name="elek_waermepumpe_leistung",
        address=33545,
        unit="kWh",
        device_class="energy",
        state_class="total",
        register=2,
        edit=False,
        enabled_by_default=True,
    ), `

**Comment by larsneo** [comment]
we are talking about different things - the ha energy dashboards shows "Energieverbrauch" over the time (day, week, month), therefore kWh is the correct unit in this case. nevertheless the unit for wallbox and heatpump itself is kW ;-)

see my dashboard an compare to the energy flow diagram in my previous post

![energie-dashboard-ha](https://github.com/user-attachments/assets/bda2257b-2361-47b9-b24a-f332d3df050c)

**Comment by larsneo** [comment]
see e.g. the Tibber entities as another example for the correct mixup of kW and kWh:

![Screenshot_20241008-101910](https://github.com/user-attachments/assets/780426c3-67fb-4bf2-94fd-8c39f031eec1)

**Comment by kwithus** [comment]
Well, again, you are absolutely right and I agree that kW would be the correct setting, however
For the power flow card it doesn’t make a difference whether kW or kWh, both works.
I still don’t understand why it makes a difference for the energy dashboard, which accepts only kWh.
Well if you prefer to have the setting in the integration to kW, that’s fine, for usage in Energy Dashboard I will then have to setup a template sensor to convert it to kWh ;-)

**Comment by HLueken** [comment]
The implementation with kW is correct since this is the **power** used by the heat pump. The Energy dashboard shows the **consumption** which is kWh. If you want to show the consumption of the heat pump you should define a integral sensor (which calculates power to consumption using time)
