### ISSUE TITLE
[BUG] Re-Configuration not possible

### ISSUE THREAD

**Issue by bufu2012** [LarsK1/hass_solvis_control#41]
**Version of the plugin**
1.10

 **Home-Assistant Version**
2024.10.2

**Enviroment (Docker, HAOS, ...)**
The enviroment your HomeAssistant is running in a virtual machine with HA OS

**Describe the bug**
When the heater is already configured & working fine, it could happen that the IP adress of the heater change due to network configuration.
After changing the IP on the heater itself, I tried to reconfigure the IP adress of the heater within HA. After entering the new IP and clicking on submit, I receive the error "Unknown error occurred"

**To Reproduce**
1. Configure add-on succesfully & use it
2. Go to Click on 'Solvis Control'
3. Click on an existing device
4. Click on 'Konfigurieren'
5. Enter new or existing IP
6. Click on 'Bestätigen'
7. (optional: Select 'HKR2 + HKR3 + Solar Kollektoren + Wärmepumpe)
8. Click on 'Bestätigen'
9. See error

**Expected behavior**
The expected behaviour is that the existig device & entities change the IP adress so that the reconfiguration is applied. After that the sensor would not be re-created so the historie of the values will be kept

![2024-10-18_08h54_28](https://github.com/user-attachments/assets/c7fd6605-820d-44a4-a448-271c1116be7f)
![2024-10-18_08h54_41](https://github.com/user-attachments/assets/1894e421-a799-4888-9d0d-eae5b9a4a466)
![2024-10-18_08h54_51](https://github.com/user-attachments/assets/0232704b-a088-4db5-91c1-f0da1a7727e7)

**Comment by LarsK1** [comment]
Fixes
