### ISSUE TITLE
[BUG] Heizkurve Steilheit editing issue

### ISSUE THREAD

**Issue by kwithus** [LarsK1/hass_solvis_control#52]
Sorry for re-opening this.
I am absolutely fine with the representation, however, with multiplier other than 1, I am not able to change the setting of the curve.
not only that the slider ‚jumps‘ to values .2 or 1. or 2 (regardless of different setting for step-size I tried) it also doesn’t send any values to Solvis.
With Multiplier 1 I am able to set values, however, there is an issue with the step size, as the value should change only in steps multiplied by 5. again, I tried different step size, nothing worked.
Funny enough, as I said, at least with Multiplier 1 I am able to change the settings, but always steps size 1 and even more strange Solvis does accept steps ‚inbetween‘ where the remote itself only does steps in 5.
Example: I have a curve of .75 (with multiplier 1 showing in HA as 75) I change this by slider to 76, looking via remote on Max I do see setting 76, when I then increase within the remote I do get 81 (step 5 increase)
So somehow we should find combination that makes it possible to change the settings in steps of 5.
There is a different issue with the SolvisPortal App, in case you are using this. Changes to the curve setting in the Portal are reflected immediately in the remote Control, changes made by the remote Control RC3 are not or at least only with very long delay shown in the Portal.
So anyone trying to find a solution should check directly in RC3
Fallback Solution: making those addresses for the curve a readonly Sensor and using the Portal or RC3 to make changes. Not as nice, but better than a not working number entity

**Comment by LarsK1** [comment]
Hi @kwithus ,
thanks for testing. I just pushed a commit. Can you please try, if that fixes it for you?

**Comment by kwithus** [comment]
Perfect, thanks! Changes are now in steps of 5, and they are reflected in the Remote. Thanks for fixing this. 

However, they do not show up in the PortalApp, at least not in a reasonable time frame, but that’s an issue of the App, as changes done in the remote neither show up in the PortalApp ;-(
