### ISSUE TITLE
[BUG] Wärmepumpenleistung wird nicht angezeigt

### ISSUE THREAD

**Issue by bufu2012** [LarsK1/hass_solvis_control#56]
**Version of the plugin**
1.1.3

**Home-Assistant Version**
2024.10.3

**Enviroment (Docker, HAOS, ...)**
Synology VM

**Describe the bug**
Die Leistung der Wärmepumpe wird nicht übermittelt. Die restlichen Werte sind vorhanden und werden auch regelmäßig aktualisiert.
Die Leistungsaufnahme sowie -Abgabe sowie die Laufleistung wurde nicht übermittelt und steht konstant auf -0,1kW. In der Solvis App hingegen habe ich die korrekten Werte (nur halt nicht in HA)

Was könnte das Problem sein?

**Comment by LarsK1** [comment]
Hi,
Bitte probiere doch einmal, ob ein Hard-Reset der Heizung hilft. Also Hauptschaltet aus, 30s warten, einschalten.

**Comment by larsneo** [comment]
p(therm) und p(elek) werden bei mir (für die Mia 14) einwandfrei in HA abgebildet, was für ein modell hast du?
![grafik](https://github.com/user-attachments/assets/b072e37c-0800-4f6b-8e72-6bfb8894fce7)

**Comment by bufu2012** [comment]
Danke für eure Antworten. @LarsK1 habe ich gemacht - leider ohne Veränderung
@larsneo habe ebenfalls die Mia 14 - bei mir schaut es derzeit so aus:
![image](https://github.com/user-attachments/assets/764a5bc9-02d9-4d2a-a368-f3b033c8e47e)

Ideen zum Debugging?

**Comment by LarsK1** [comment]
@bufu2012 führe gerne einmal ein Update auf die 1.1.4 durch und aktiviere dann einmal den Debug-Modus und schick hier einmal die Logs rein.

**Comment by bufu2012** [comment]
Sorry für die späte Rückmeldung - sind mitten in der Renovierung

Ich kann leider nicht sagen warum, aber es funktioniert jetzt.
In der Zwischenzeit wurde etwas am Netzwerk geändert, alle Geräte diverse
Male neugestartet, etc.

Jetzt funktioniert jedenfalls die Anzeige.

Danke euch!!



Andreas Krapohl ***@***.***> schrieb am Do. 7. Nov. 2024 um
13:42:

**Comment by larsneo** [comment]
schön zu hören, beim homeassistant gilt tatsächlich oftmals ganz einfach das AEG prinzip - ausschalten, einschalten, geht.
