### ISSUE TITLE
[BUG] Problem updating

### ISSUE THREAD

**Issue by MAPSOFT2** [LarsK1/hass_solvis_control#57]
I'm on Version on Version 1.1.3 and don't know how to Update. It is not automatically detected and wenn I look on the integration screen I only see:
![image](https://github.com/user-attachments/assets/aa8bf74e-86b9-4be3-b394-cc3bb7c71b1b)

For the last Versions I had the same or at least similar problems.

**Comment by LarsK1** [comment]
Hi @MAPSOFT2,
didn't get such feedback from anybody else. Usually it can take up to 48h, until the Github Release has been duplicated to the HASS mirror.
