### ISSUE TITLE
Home Assistant failed to connect

### ISSUE THREAD

**Issue by ThomasWollstadt** [LarsK1/hass_solvis_control#6]
Latest version of  solvis control is installed.
HomeAssistant-Version latest is installed running on a PI4
Solvis VC3 is connected via LAN and communicates properly with Solvis portal. It is connected via a switch with my Fritzbox.
IP Address and port 502 is set properly in the configuration of Solvis Control

Nevertheless I get a failed to connect after reboot of heating system or Homeassistant every time.

Any idea where to search for the root cause?

**Comment by LarsK1** [comment]
Hi @ThomasWollstadt ,
did you enable the modbus interface one the Solvis in the "Installateur"-Menu?

**Comment by ThomasWollstadt** [comment]
… yes… 

 

Interestingly: I switched from LAN to WLAN connection on the SOLVIS side yesterday and now it works without any other adaptations… not sure how to inteprete this…

 

Von: Lars Kusch ***@***.***> 
Gesendet: Donnerstag, 27. Juni 2024 10:03
An: LarsK1/hass_solvis_control ***@***.***>
Cc: ThomasWollstadt ***@***.***>; Mention ***@***.***>
Betreff: Re: [LarsK1/hass_solvis_control] Home Assistant failed to connect (Issue #6)

 

Hi @ThomasWollstadt <https://github.com/ThomasWollstadt>  ,
did you enable the modbus interface one the Solvis in the "Installateur"-Menu?

**Comment by LarsK1** [comment]
Hi,
never experienced such an issue. I'm personally using my Solvis over LAN without any troubles...
