### ISSUE TITLE
[BUG] Problem with update to 1.1.7

### ISSUE THREAD

**Issue by larsneo** [LarsK1/hass_solvis_control#60]
**Version of the plugin**
1.1.7

 **Home-Assistant Version**
2024.11.3

**Enviroment (Docker, HAOS, ...)**
HA green

**Describe the bug**
Various entities disappear with update from 1.1.4 to 1.1.7

**To Reproduce**
update to 1.1.7

**Expected behavior**
all entites remain available

**Screenshots**
![ha 114](https://github.com/user-attachments/assets/f8dc0db6-e359-40bf-9466-76ac2ccebce9)
![ha 117](https://github.com/user-attachments/assets/8a297776-1ddb-4f2b-9119-bf9b9718296d)

**Additional context**
Beim Update auf 1.1.7 verschwinden diverse Entitäten, insbesondere die Angaben zur Wärmepumpe. Auch Neustart von HA bzw. Löschen und Neunanlegen des Gerätes machen keinen Unterschied. Firmware der Steuerung: MA3.19.47. Downgrade to 1.1.4 bringt alle Entitäten zurück,

**Comment by LarsK1** [comment]
Hi @larsneo ,
danke für deine Rückmeldung.

Das verstehe ich nicht. Bei mir sind alle Entitäten noch sichtbar - derweil auch die gleiche Firmware-Version...

Kannst Du bitte noch einmal upgraden und dann den Debug-Log einschalten?

**Comment by LarsK1** [comment]
HI @larsneo ,
alles zurück - der Bug sitzt wie immer vor dem PC... Zieh dir mal die neuste Version, damit sollte der Fehler weg sein ...
