### ISSUE TITLE
[BUG] Sensor values are inverted

### ISSUE THREAD

**Issue by tinkerberlin** [LarsK1/hass_solvis_control#7]
**Version of the plugin**
1.0.1

 **Home-Assistant Version**
2024.7.0b5

**Enviroment (Docker, HAOS, ...)**
HAOS

**Describe the bug**
Some sensors are being pulled in inverted from the value being reported on the Solvis Control unit. 
For example: 
<img width="239" alt="image" src="https://github.com/LarsK1/hass_solvis_control/assets/99590368/097a65e8-ac18-4b7b-a339-fada76e307f4">
The value here is reported as nearly negative 70°C. In the SC unit directly the value is correctly reported at nearly positive 70°C.

The sensor of the example here is the "lower" ("unten") Pufferspeicher-Sensor. The "upper" ("oben") Sensor is correctly reporting the positive temperature value - as expected. 

Another example is the number of restarts of the heater. 
<img width="230" alt="image" src="https://github.com/LarsK1/hass_solvis_control/assets/99590368/f3e13108-8a20-43f2-97e5-d571f5a90a92">
(disregard the high value - this is a problem with my heater which is being investigated by Solvis technical support.)

**To Reproduce**
Not sure how to reproduce. This is simply how the sensor's value is being displayed for me...

**Expected behavior**
I would expect the integration to show the values as reported by the SC unit.

**Screenshots**
<img width="239" alt="image" src="https://github.com/LarsK1/hass_solvis_control/assets/99590368/9c714b70-f743-49ca-9cd2-c9147dfad29e"> (same screenshot as above)

**Comment by LarsK1** [comment]
Hallo!
Danke für deine Meldung. Das ist ja lustig. Ich kenne diese Werte derweil in x-verschiedenen Varianten. Welches Modell von Heizung bzw. welche Firmwareversion hast du denn?

**Comment by tinkerberlin** [comment]
Hallo! Danke für die schnelle Antwort.
Es handelt sich um die SolvisMax.
Ich glaube die FW Version ist 3.18.14 - kommt das hin?

**Comment by HLueken** [comment]
Ich habe das gleiche Problem, mit "sensor.solvis_heizung_heizungspuffertemperatur_unten".
Ich habe Solvis Max mit Wärmepumpe Lea Premium, SC3, FW Version 3.19.47

**Comment by LarsK1** [comment]
Bugfix is available in: https://github.com/LarsK1/hass_solvis_control/commit/07cee47fe7f7a52233543b7807cb0a8a83460704

**Comment by LarsK1** [comment]
Gerne einmal mit dem neuen Release testen.

**Comment by HLueken** [comment]
Dein Fix hat mein Problem mit sensor.solvis_heizung_heizungspuffertemperatur_unten bereinigt, der Wert passt jetzt!
Vielen Dank!

**Comment by LarsK1** [comment]
@tinkerberlin kannst du bitte auch noch einmal testen und bestätigen, dass das Problem bei dir auch behoben ist?

**Comment by LarsK1** [comment]
Hi @tinkerberlin,
nein. Leider hat uns schon ein Solvis-Techniker gesagt, dass die Modbus-Schnittstelle normalerweise nur im 30 Minuten-Takt genutzt wird. Da wir diese aber alle 30s abfrage kommt es immer mal wieder zu kleinen Problemen. Aber so häufig wie bei dir kann ich es nicht feststellen.
