### ISSUE TITLE
Values of heat pump

### ISSUE THREAD

**Issue by HLueken** [LarsK1/hass_solvis_control#9]
This software works great in my installation. I have installed a SolvisMax, SC-3, and a Lea Premium heat pump.

All values fron SolvisMax are reported, this is cool.

Would it be possible to show also values from the Lea Premium heat pump? Unfortunately I did not find any Modbus documentation for these values.

I would be interested in the following values:
- elektrische Energie Wärmepumpe
- Wärmemenge Wärmepumpe
- Startvorgänge Wärmepumpe
- Leistung Wärmepumpe
- Laufzeit Wärmepumpe
- Wärmemenge Heizstab
- Startvorgänge Heizstab
- Laufzeit Heizstab

**Comment by LarsK1** [comment]
Hallo @HLueken ,
danke erst einmal für dein Lob. Werden den die Werte über das Solvis Portal angezeigt?
https://solvisportal.de/account

**Comment by HLueken** [comment]
Werden sie, teils bei den Sensoren, teils im Überblick, teils bei den Bilanzen

![IMG_0891](https://github.com/user-attachments/assets/b2cb9c62-78c6-48b6-adf6-bcf4a778525c)
![IMG_0890](https://github.com/user-attachments/assets/ce466165-20f6-4fbf-9b3d-97a4ab049501)
![IMG_0889](https://github.com/user-attachments/assets/289065ee-f9ce-4845-8c71-007f92b860c3)

**Comment by kwithus** [comment]
Moin,
Ich hänge mich hier gerne an diesen Wunsch an, auch wenn es bei mir die Solvis Mia Wärmepumpe ist.

**Comment by LarsK1** [comment]
Hi,
über Modbus ist das leider nicht realisierbar, da Solvis diese Daten (nach meinem Wissen) nicht freigibt. Es wird aber in der Zukunft eine V2 geben über das Solvis Portal, dort würde das dann gehen.

**Comment by kwithus** [comment]
Ich habe einmal bei Solvis nachgefragt, ob und wenn ja wie die Daten der Wärmepumpe über Modbus abfragbar sind, werde dann berichten. (Wenn Solvis antwortet)

**Comment by HLueken** [comment]
Wenn du irgendwann deine Lösung erweitern kannst (V2, Modbus, …), biete ich mich gerne zum Testen an).

**Comment by kwithus** [comment]
Laut Solvis wird das Register derzeit überarbeitet. Mehr Auskunft war leider nicht zu bekommen

**Comment by zefu59** [comment]
Die besonders interessanten Werte für Wärmepumpenbesitzer habe ich experimentell herausgefunden und mit dem Solvisportal verifiziert:
address=33544 => Wärmepumpenleistung
address=33545 => elektrische Wärmepumpenleistung
Hatte die auch schon mal erfolgreich in const.py eingebaut, aber aus Angst vor Update-Konflikten, mit dieser von mir sehr geschätzten HA-Integration, wieder entfernt. Vielleicht kann das ja ins nächste Update integriert werden ;-)

**Comment by zefu59** [comment]
> Laut Solvis wird das Register derzeit überarbeitet. Mehr Auskunft war leider nicht zu bekommen

Ich hatte die auch mal angeschrieben und höflich gefragt - keine Antwort seit mehreren Wochen (muss man mindestens als unhöflich bezeichnen). In verschiedenen Foren habe ich über Monate verschiedene Berichte über nicht beantwortete Anfragen gelesen, ebenso (schon vor Monaten), dass man die Doku gerade überarbeitet ...

**Comment by zefu59** [comment]
> Hi, über Modbus ist das leider nicht realisierbar, da Solvis diese Daten (nach meinem Wissen) nicht freigibt. Es wird aber in der Zukunft eine V2 geben über das Solvis Portal, dort würde das dann gehen.

Das Solvis Portal zu benutzen, setzt aber voraus, dass die Anlage eine permanente Internetverbindung hat. Das wollte ich persönlich gerne gerade durch den Einsatz des HA vermeiden. Für die Störungssuche oder Softwareupdates würde ich natürlich (temporär) den Internetkontakt erlauben.

**Comment by LarsK1** [comment]
@zefu59 in welcher Einheit liegen denn die beiden Modbus-Werte vor. Bzw. in welcher Einheit sollte dieser Wert ausgegeben werden? So wie im PR?

**Comment by zefu59** [comment]
@LarsK1 beide werden in kW gemessen (siehe "Übersicht" im Solvis-Portal, was ich zur Verifizierung der Adressen genutzt habe)

**Comment by kwithus** [comment]
> Ich hatte die auch mal angeschrieben und höflich gefragt - keine Antwort seit mehreren Wochen (muss man mindestens als unhöflich bezeichnen). In verschiedenen Foren habe ich über Monate verschiedene Berichte über nicht beantwortete Anfragen gelesen, ebenso (schon vor Monaten), dass man die Doku gerade überarbeitet 
> 

Ja, Antworten dauern etwas, aber ich habe jeweils nach 1-2 Wochen eine Antwort bekommen, wenn auch nicht wirklich aussagekräftig ;-)



> Die Register für die Zeitfenster von WW (34174-34215) und Zirku (34216-34257), sowie ECO-Funktion (34258-34299) sind fehlerhaft. Somit gibt es Adressen die noch nicht zur Verfügung stehen und welche, die geprüft werden.
Es wird mit Sicherheit ein Release geben, wo das alles gefixt ist und auch vollständig ist. Die Prog. Prio liegt aktuell jedoch auf anderen Dingen, daher wird es dieses Jahr mit Sicherheit nicht mehr vervollständigt und getestet.

> 

Klingt aber zumindest für die Zukunft vielversprechend

**Comment by HLueken** [comment]
Ich habe es jetzt auch vor ein paar Tage installiert, scheint gut zu funktionieren. Zwei Änderungen waren notwendig in const.py: 
- Unit in kW geändert
- device_class in power geändert

Vielen Dank für den Einbau!!!

![IMG_0937](https://github.com/user-attachments/assets/ab726284-9831-4063-9cc2-617dd70e32c4)
